package org.intocps.maestro;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

public class Issue188Test {

    @Disabled("Causes issue on github action via maven surefire. HOwever, the spec is the one generated by the test " +
            "CreateAndInterpretNewSpec() so the scenario is still covered.")
    @Test
    public void InterpretSpec() throws Exception {
        Assertions.assertTrue(Main.argumentHandler(new String[]{"-i", Issue188Test.class.getClassLoader().getResource("188/spec.mabl").getPath()}));
    }

    @Disabled
    @Test
    public void CreateAndInterpretNewSpec() throws Exception {
        String initializeJson = Issue188Test.class.getClassLoader().getResource("188/initialize.json").getPath();
        String simulateJson = Issue188Test.class.getClassLoader().getResource("188/simulate.json").getPath();
        String dumpPath = "target/test-classes/188/dump";
        Assertions.assertTrue(Main.argumentHandler(new String[]{"-sg1", initializeJson, simulateJson, "-ds", dumpPath}));
    }

}
