name: Docs
on: [ push, pull_request, workflow_dispatch ]
permissions:
  contents: write
env:
  JAVA_VERSION: 11.0.3
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install dependencies
        run: |
          cd docs
          pip install sphinx sphinx_rtd_theme
          pip install -r requirements.txt
      - name: Sphinx build
        run: |
          pwd
          cd docs
          ls
          sphinx-build . _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
